#!/usr/bin/env bash
# This script loops from 1 to 20 and uses a case statement to display
# specific messages for certain "unlucky" numbers.

counter=1
while [ $counter -le 20 ]
do
    echo "$counter"
    case "$counter" in
        4)
            echo "bad luck from China"
            ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
            ;;
    esac
    counter=$((counter + 1))
done
